<?php
# This file was automatically generated by the MediaWiki 1.29.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "단어위키";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wiki";
$wgScriptExtension = ".php";
$wgArticlePath = "/word/$1";
$wgUsePathInfo = true;

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wordwiki.net";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/event/wiki.png";
$wgFavicon = "$wgResourceBasePath/images/boseong.ico";

## UPO means: this is also a user preference option

$wgEmergencyContact   = "admin@mailto.kro.kr";
$wgEnableUserEmail = true; # UPO

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "wordwiki.net";
$wgDBname = "c180wiki";
$wgDBuser = "c180wordwiki";
$wgDBpassword = "00030003";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgGenerateThumbnailOnParse = true;
$wgMaxImageArea = 4.9e7;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "ko";

$wgSecretKey = "bd527fbaabef117255c8ce8d7ecd7515fef39935335a09ef662acc3a3b8c2b99";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "db708f7099de7a73";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://wordwiki.net/word/%EB%8B%A8%EC%96%B4%EC%9C%84%ED%82%A4:%EC%A0%80%EC%9E%91%EA%B6%8C";
$wgRightsText = "CC-BY-SA 4.0";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "Timeless";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Vector' );
wfLoadSkin( 'Liberty' );
wfLoadSkin( 'Timeless' );
# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
# gadgets 제거
#wfLoadExtension( 'ImageMap' ); 삭-제 6/25
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'SpamBlacklist' );
#wfLoadExtension( 'SyntaxHighlight_GeSHi' ); 원인모를 작동 오류로 제-거 6/25
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'EmbedVideo' );
#wfLoadExtension( 'ConfirmEdit' ); 7/6
/* wfLoadExtension( 'ConfirmEdit/ReCaptchaNoCaptcha' );
$wgCaptchaClass = 'ReCaptchaNoCaptcha';
$wgReCaptchaSiteKey = '6LeI_0gUAAAAADNbUhFk1etthpTkOqOcARcs4pSU';
$wgReCaptchaSecretKey = '6LeI_0gUAAAAACkpgt4Lbcx8eaMQeC4axCvrY4zv'; */


# End of automatically generated settings.
# Add more configuration options below.

require_once "$IP/extensions/NamuMark/namumark.php";
$wgRawHtml = true;
$wgAllowImageTag = true;
$wgNamespacesWithSubpages[NS_MAIN] = true;
$wgNamespacesWithSubpages[NS_TEMPLATE] = true;
$wgAllowDisplayTitle = true;
$wgRestrictDisplayTitle = false;
#$wgDefaultUserOptions['numberheadings'] = 1;

# WikiEditor
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;
$wgDefaultUserOptions['wikieditor-publish'] = 0;

require_once "$IP/extensions/UserGroups/UserGroups.php";


// 내가 추가할 이름공간에 대한 상수를 정의합니다.
define("NS_TEMP", 32); // 이 상수는 반드시 짝수여야 합니다.
define("NS_TEMP_TALK", 33); // 이 값은 반드시 따라나오는(following) 홀수여야 합니다. (*역주: 따라나오는 홀수란 짝수 n의 바로 다음 수인 n+1을 말합니다.)

// 이름공간을 추가합니다.
$wgExtraNamespaces[NS_TEMP] = "서식";
$wgExtraNamespaces[NS_TEMP_TALK] = "서식_개선"; // 이름공간 이름의 밑줄에 주목하십시오.

// 내가 추가할 이름공간에 대한 상수를 정의합니다.
define("NS_KNOW", 34); // 이 상수는 반드시 짝수여야 합니다.
define("NS_KNOW_TALK", 35); // 이 값은 반드시 따라나오는(following) 홀수여야 합니다. (*역주: 따라나오는 홀수란 짝수 n의 바로 다음 수인 n+1을 말합니다.)

// 이름공간을 추가합니다.
$wgExtraNamespaces[NS_KNOW] = "지식";
$wgExtraNamespaces[NS_KNOW_TALK] = "지식_의견"; // 이름공간 이름의 밑줄에 주목하십시오.

// 내가 추가할 이름공간에 대한 상수를 정의합니다.
define("NS_OPIN", 36); // 이 상수는 반드시 짝수여야 합니다.
define("NS_OPIN_TALK", 37); // 이 값은 반드시 따라나오는(following) 홀수여야 합니다. (*역주: 따라나오는 홀수란 짝수 n의 바로 다음 수인 n+1을 말합니다.)

// 이름공간을 추가합니다.
$wgExtraNamespaces[NS_OPIN] = "의견";
$wgExtraNamespaces[NS_OPIN_TALK] = "의견_토론"; // 이름공간 이름의 밑줄에 주목하십시오.


define("NS_Project", 38);
define("NS_Protalk", 39);

$wgExtraNamespaces[NS_Project] = "동아리";
$wgExtraNamespaces[NS_Protalk] = "동아리방";

define("NS_GEUL", 40);

$wgExtraNamespaces[NS_GEUL] = "글";



$wgShowExceptionDetails = true;


$wgNamespacesWithSubpages[NS_SERIES] = true;            // foo 이름공간에 대해 하위 문서(subpage)를 활성화 합니다.
$wgNamespacesWithSubpages[NS_KNOW] = true;            // foo 이름공간에 대해 하위 문서(subpage)를 활성화 합니다.
$wgNamespacesWithSubpages[NS_OPIN] = true;            // foo 이름공간에 대해 하위 문서(subpage)를 활성화 합니다.
$wgNamespacesWithSubpages[NS_OPIN_TALK] = true;
$wgNamespacesWithSubpages[NS_TEMP] = true;            // foo 이름공간에 대해 하위 문서(subpage)를 활성화 합니다.
$wgNamespacesWithSubpages[NS_GEUL] = true;
$wgNamespacesWithSubpages[NS_GEUL_TALK] = true;

wfLoadExtension ( 'AntiSpoof' );
wfLoadExtension ( 'AbuseFilter' );

wfLoadExtension( 'EditAccount' );

wfLoadExtension( 'NewUserMessage' );

wfLoadExtension( 'WikiForum' );

// flow 설치를 위한
// 그러나 실패
// 삽질 후 LQT로 복귀
// 2018 05 26
wfLoadExtension( 'cldr' );
wfLoadExtension( 'CheckUser' );
require_once "$IP/extensions/LiquidThreads/LiquidThreads.php";
$wgShowDBErrorBacktrace = true;

wfLoadExtension( 'SimpleMathJax' );
#require_once 'Google/autoload.php';
#require_once "$IP/extensions/GoogleLogin/GoogleLogin.php";
#$wgGLAppId = '1080467613305-8p1qbuot0gatdftrse3p63t8a6opfs2s.apps.googleusercontent.com';
#$wgGLSecret = 'd6of3dDGOCMwI4ECLGdzLP8z';

$wgEnableEmail = true;
$wgSMTP = [
 'host' => 'ssl://smtp.gmail.com',
 'IDHost' => 'wordwiki.net',
 'port' => 465,
 'username' => 'wordwikiofficial@gmail.com',
 'password' => 'namulibe',
 'auth' => true,
];
// 20180723 설공의 이메일 작업

$wgGroupPermissions['*']['edit']              = false;
$wgGroupPermissions['user']['edit']           = false;
$wgAutopromote['emailconfirmed'] = APCOND_EMAILCONFIRMED;
$wgImplicitGroups[] = 'emailconfirmed';
$wgGroupPermissions['emailconfirmed']['edit'] = true;
// 20180724 설공의 이메일 인증된 사용자만 편집가능하게 제한 작업
$wgSpamBlacklistFiles = array(
   "[[m:Spam blacklist]]",
   "https://en.wikipedia.org/wiki/MediaWiki:Spam-blacklist"
);
// 20180724 이메일 차단 필터
$wgAllowExternalImages = true;
// 20180906 역할 수정
$wgGroupPermissions['editunable']['edit'] = false;
$wgAutoConfirmAge = 86400*7;
// 20181007 찾아바꾸기 프로그램 대체
require_once "$IP/extensions/MassEditRegex/MassEditRegex.php";